from __future__ import annotations

import pickle
import sys
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

ROOT = Path(__file__).resolve().parent
SRC_DIR = ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from diabetesPredictor.config.configuration import model_path

FEATURE_COLUMNS = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
]

class DiabetesFeatures(BaseModel):
    Pregnancies: int = Field(..., ge=0)
    Glucose: int = Field(..., ge=0)
    BloodPressure: int = Field(..., ge=0)
    SkinThickness: int = Field(..., ge=0)
    Insulin: int = Field(..., ge=0)
    BMI: float = Field(..., ge=0)
    DiabetesPedigreeFunction: float = Field(..., ge=0)
    Age: int = Field(..., ge=0)


def load_pipeline_model() -> Any:
    """Load the model produced by the DVC `train` stage.

    Serving must not retrain from raw data: that would bypass the DVC split and
    parameters and can yield a model different from the tracked pipeline output.
    """
    if not model_path.is_file():
        raise RuntimeError(
            f"DVC model artifact not found at {model_path}. "
            "Run 'dvc repro train' (or 'dvc repro') before starting the API."
        )

    try:
        with model_path.open("rb") as file:
            model = pickle.load(file)
    except (OSError, pickle.UnpicklingError) as error:
        raise RuntimeError(f"Unable to load DVC model artifact at {model_path}") from error

    required_methods = ("predict", "predict_proba")
    if not all(callable(getattr(model, method, None)) for method in required_methods):
        raise RuntimeError("DVC model artifact is not a compatible probabilistic classifier.")
    return model


@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.model = load_pipeline_model()
    yield


app = FastAPI(
    title="Diabetes Predictor API",
    description="Serves the model generated by the DVC training pipeline.",
    version="1.0.0",
    lifespan=lifespan,
)


@app.get("/", tags=["root"])
async def read_root():
    return {
        "message": "Diabetes predictor API is running.",
        "model_path": str(model_path),
        "features": FEATURE_COLUMNS,
    }


@app.get("/health", tags=["health"])
async def health():
    return {"status": "ok", "model_loaded": app.state.model is not None}


@app.get("/model/features", tags=["model"])
async def model_features():
    return {"features": FEATURE_COLUMNS}


@app.post("/predict", tags=["predict"])
async def predict(features: DiabetesFeatures):
    try:
        # Explicitly preserve the exact training-column order used by DVC.
        frame = pd.DataFrame([features.model_dump()], columns=FEATURE_COLUMNS)
        prediction = int(app.state.model.predict(frame)[0])
        probability = float(app.state.model.predict_proba(frame)[0][1])

        if probability >= 0.6:
            risk_level = "high"
        elif probability >= 0.4:
            risk_level = "moderate"
        else:
            risk_level = "low"

        return {
            "prediction": prediction,
            "probability": probability,
            "risk_level": risk_level,
            "diabetes": bool(prediction),
        }
    except (AttributeError, IndexError, KeyError, TypeError, ValueError) as exc:
        raise HTTPException(status_code=500, detail="Prediction failed.") from exc
